spring.application.name=mcp-client-fotova

#### OLLAMA ####
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.2

spring.ai.mcp.client.name=mcp-fotova
spring.ai.mcp.client.version=1.0.0a
spring.ai.mcp.client.toolcallback.enabled=true
spring.ai.mcp.client.sse.connections.fotova-server.url=http://localhost:8082/sse

spring.datasource.url=jdbc:sqlite:C:/Users/thoma/IdeaProjects/mcp-client-fotova/data/fotova-mcp.db
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update